# -*- coding: utf-8 -*-
"""Atividade N1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dW4OjD6SpW1AFJPD7gxGY7wVImpVthm9
"""

n1 = float(input('primeira nota '))
n2 = float(input('segunda nota '))
n3 = float(input('terceira nota'))


media = (n1+n2+n3)/3
if (media>=7):
    sit= 'aprovado'
elif(media>=4):
    sit ='reprovado'
else:
    sit = 'para final'
print(f'situação do aluno é {sit} ')